package mission.runner;

import mission.config.ConfigReader;
import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;
import org.testng.ISuite;
import org.testng.ISuiteListener;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 * TestNG Suite listener that generates Masterthought
 * Generate HTML report after all tests complete.
 * Reads CucumberTestReport.json generated by Cucumber
 * and produces a rich HTML dashboard.
 */

public class CucumberReportListener implements ISuiteListener {
    @Override
    public void onStart(ISuite suite) {
        // Nothing needed before suite starts
    }

    @Override
    public void onFinish(ISuite suite) {
        generateReport();
    }

    private void generateReport() {
        String jsonReportPath = "test-output/cucumber-reports/"
                + "CucumberTestReport.json";

        // Standard Maven build output directory
        File reportOutputDir = new File(
                "target/cucumber-reports/advanced-reports");

        // Create output directory if it doesn't exist
        if (!reportOutputDir.exists()) {
            reportOutputDir.mkdirs();
        }

        // Check JSON report exists before generating
        File jsonFile = new File(jsonReportPath);
        if (!jsonFile.exists()) {
            System.out.println("Cucumber JSON report not found at: "
                    + jsonReportPath);
            return;
        }

        List<String> jsonFiles = new ArrayList<>();
        jsonFiles.add(jsonReportPath);

        Configuration config = new Configuration(
                reportOutputDir, "Mission QA Automation");

        // Dynamic values — read from config and system
        // Browser read from TestData.properties via ConfigReader
        config.addClassifications("Browser",
                ConfigReader.getProperty("Browser"));
        config.addClassifications("Environment", "Test");
        config.addClassifications("Platform",
                System.getProperty("os.name"));
        config.addClassifications("Framework",
                "Selenium 4 + Cucumber 7 + TestNG");

        ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, config);
        reportBuilder.generateReports();

        System.out.println("==============================================");
        System.out.println("Masterthought Report generated at:");
        System.out.println(reportOutputDir.getAbsolutePath()
                + "/cucumber-html-reports/overview-features.html");
        System.out.println("==============================================");
    }
}
